name: 02. Publish Rust Container Images

on:
  push:
    tags: [ 'v*.*.*' ]
  workflow_run:
    workflows: ["Rust Build & Test"]
    types: [completed]

jobs:
  check-version:
    if: startsWith(github.ref, 'refs/tags/v')
    name: Ensure GitHub Release & Cargo.toml Version Numbers Match
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check Cargo Version Matches Tag
        uses: spice-labs-inc/action-check-version@main

  build:
    name: Build Rust Binary
    needs: check-version
    uses: spice-labs-inc/action-build-rust/.github/workflows/rust-build.yml@main
    with:
      working_directory: .
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      GH_USERNAME_SG: ${{ secrets.GH_USERNAME_SG }}

  publish-dockerhub:
    name: Publish to Docker Hub
    needs: build
    uses: spice-labs-inc/action-publish-image-dockerhub/.github/workflows/publish-dockerhub.yml@main
    with:
      image_name: ${{ github.event.repository.name }}
      dockerfile: Dockerfile
      context: .
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

  publish-ghcr:
    name: Publish to GHCR
    needs: build
    uses: spice-labs-inc/action-publish-image-ghcr/.github/workflows/publish-ghcr.yml@main
    with:
      image_name: ${{ github.event.repository.name }}
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      GH_USERNAME: ${{ secrets.GH_USERNAME_SG }}

  grinder-scan:
    name: Run Spice Grinder Scan
    needs: publish-ghcr
    runs-on: ubuntu-24.04
    steps:
      - name: Download Compiled Binary
        uses: actions/download-artifact@v4
        with:
          name: ginger-binary
          path: target/release

      - name: Download OCI Tar Image
        uses: actions/download-artifact@v4
        with:
          name: docker-artifacts
          path: target/release

      - name: Run Spice Grinder Scan
        uses: spice-labs-inc/action-grinder-scan@main
        with:
          file_path: target/release/
          spice_pass: ${{ secrets.GRINDER_JWT }}

  attest:
    name: Image Attestation
    needs: publish-ghcr
    uses: spice-labs-inc/action-attest-image/.github/workflows/attest-image.yml@main
    with:
      subject_name: ghcr.io/spice-labs-inc/ginger
      subject_digest: ${{ needs.publish-ghcr.outputs.digest }}
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      GH_USERNAME: ${{ secrets.GH_USERNAME_SG }}
