name: 02. Publish Rust Container Images

on:
  push:
    tags: [ 'v*.*.*' ]
  workflow_run:
    workflows: ["01. Rust Build & Test"]
    types: [completed]
    branches: [main]

jobs:
  check-version:
    if: startsWith(github.ref, 'refs/tags/v')
    name: Ensure GitHub Release & Cargo.toml Version Numbers Match
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check Cargo Version Matches Tag
        uses: spice-labs-inc/actions/cargo_version_check@main

  push_to_registry:
    name: Push Docker Image to Docker Hub and GHCR
    runs-on: ubuntu-24.04
    needs: check-version

    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write

    steps:
      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Checkout with LFS
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Set Up Rust Toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Cargo Dependencies
        uses: Swatinem/rust-cache@v2

      - name: Build Project
        run: cargo build --release

      - name: Log In to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Log In to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Extract Metadata (Tags, Labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/spice-labs-inc/${{ github.event.repository.name }}
            spicelabs/${{ github.event.repository.name }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Build and Push Docker Image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          provenance: mode=max
          sbom: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Generate Artifact Attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ghcr.io/spice-labs-inc/${{ github.event.repository.name }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true

      - name: Save Docker Image to Tar Archive
        run: |
          image_tag=$(echo "${{ steps.meta.outputs.tags }}" | head -n1)
          image_tag=${image_tag:-ghcr.io/spice-labs-inc/${{ github.event.repository.name }}:latest}
          echo "Saving image: $image_tag"
          docker pull "$image_tag"
          docker save "$image_tag" -o ginger.tar

      - name: Compute SHA256 of Image
        run: sha256sum ginger.tar > ginger.tar.sha256

      - name: Upload Docker Image Tarball and SHA
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: |
            ginger.tar
            ginger.tar.sha256

      - name: Upload SBOM (Generated by Docker)
        uses: actions/upload-artifact@v4
        with:
          name: docker-sbom
          path: /tmp/sbom.spdx.json

      - name: Download Grinder Script
        run: |
          curl -sSL https://raw.githubusercontent.com/spice-labs-inc/grinder/dlp/cleanup/grinder.sh -o grinder.sh
          chmod +x grinder.sh

      - name: Run Spice Grinder Scan
        run: |
          mkdir -p output
          mv ginger.tar output/
          SPICE_PASS=${{ secrets.GRINDER_JWT }} ./grinder.sh --command run --input output

      - name: Upload Scan Results
        uses: actions/upload-artifact@v4
        with:
          name: spice-grinder-report
          path: spice_grinder_report.json
